###########################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# imitations under the License.
###########################################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: kappnav-init-pre
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    metadata:
      name: app-nav-init 
      labels:
        app-nav-component: app-nav-init      
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
      containers:
      - name: kappnav-init
        image: "{{ .Values.appNavInit.repository }}:{{ .Values.appNavInit.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}    
        env: 
        - name: HOOK_MODE
          value: preinstall
        - name: KUBE_ENV        
          value: {{ .Values.env.kubeEnv }}
        - name: KAPPNAV_CONFIG_NAMESPACE
          value: {{ .Release.Namespace }}
{{ include "kappnav.container.security" . | indent 8 }}
        resources:
          {{- if .Values.appNavInit.resources.constraints.enabled }}
          limits:
{{ toYaml .Values.appNavInit.resources.limits | indent 12 }}
          requests:
{{ toYaml .Values.appNavInit.resources.requests | indent 12 }}
          {{- end }}  
      restartPolicy: Never
      serviceAccountName: helm-operator
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .}}
      - name: {{ . }}
      {{- end }}
{{ include "kappnav.pod.security" . | indent 6 }}
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
