apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kindactionmappings.actions.kappnav.io
spec:
  group: actions.kappnav.io
  names:
    kind: KindActionMapping
    listKind: KindActionMappingList
    plural: kindactionmappings
    shortNames:
    - kam
    - kams
    singular: kindactionmapping
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            mappings:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  mapname:
                    type: string
                  name:
                    type: string
                  owner:
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      uid:
                        type: string
                    type: object
                  subkind:
                    type: string
                type: object
              type: array
            precedence:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int64
              type: integer
            sectionMappings:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  mapname:
                    type: string
                  name:
                    type: string
                  owner:
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      uid:
                        type: string
                    type: object
                  subkind:
                    type: string
                type: object
              type: array
            statusMappings:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  mapname:
                    type: string
                  name:
                    type: string
                  owner:
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      uid:
                        type: string
                    type: object
                  subkind:
                    type: string
                type: object
              type: array
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
