apiVersion: kappnav.operator.kappnav.io/v1
kind: Kappnav
metadata:
  name: kappnav
spec:

  ###############################################################################
  ## Environmental variables
  ###############################################################################
  env:
    kubeEnv: minikube