apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappnav-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kappnav-operator
  template:
    metadata:
      labels:
        name: kappnav-operator
    spec:
      serviceAccountName: kappnav-operator
      containers:
        - name: kappnav-operator
          # Replace this with the built image name
          image: kappnav/operator:KAPPNAV_VERSION
          command:
          - kappnav-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kappnav-operator"
