apiVersion: v1
kind: ConfigMap
metadata:
  name: kappnav.actions.application.kappnav
data:
  cmd-actions: |
    [
      {
        "name": "app-nav-inventory",
        "text": "Inventory",
        "text.nls": "action.cmd.kappnav.inventory.text",
        "description": "Take inventory of all kappnav resources.",
        "description.nls": "action.cmd.kappnav.inventory.desc",
{{ if tagContains .Spec.ExtensionContainers.appNavInv.Tag ":" }}
        "image": "{{ .Spec.ExtensionContainers.appNavInv.Repository }}@{{ .Spec.ExtensionContainers.appNavInv.Tag }}",
{{ else }}
        "image": "{{ .Spec.ExtensionContainers.appNavInv.Repository }}:{{ .Spec.ExtensionContainers.appNavInv.Tag }}",
{{ end }}
        "cmd-pattern": "./inventory.sh"
      }
    ]